version: "3"

services:
  backend:
    image: jamesaudretsch/liveit:latest
    ports:
      - "80:8000"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
    command: flask run --host=0.0.0.0 --port=8000

  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db